import type { ILanguage } from "./index";

export const ISO_639_1: ILanguage[] = [
        {
                identifiers: ["aar"],
                names: ["Afar"],
                alpha2: "aa",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["abk"],
                names: ["Abkhazian"],
                alpha2: "ab",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["afr"],
                names: ["Afrikaans"],
                alpha2: "af",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["aka"],
                names: ["Akan"],
                alpha2: "ak",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["amh"],
                names: ["Amharic"],
                alpha2: "am",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ara"],
                names: ["Arabic"],
                alpha2: "ar",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["arg"],
                names: ["Aragonese"],
                alpha2: "an",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["asm"],
                names: ["Assamese"],
                alpha2: "as",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ava"],
                names: ["Avaric"],
                alpha2: "av",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ave"],
                names: ["Avestan"],
                alpha2: "ae",
                scope: "Individual",
                type: "Historical",
        },
        {
                identifiers: ["aym"],
                names: ["Aymara"],
                alpha2: "ay",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["aze"],
                names: ["Azerbaijani"],
                alpha2: "az",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["bak"],
                names: ["Bashkir"],
                alpha2: "ba",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["bam"],
                names: ["Bambara"],
                alpha2: "bm",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["bel"],
                names: ["Belarusian"],
                alpha2: "be",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ben"],
                names: ["Bengali"],
                alpha2: "bn",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["bis"],
                names: ["Bislama"],
                alpha2: "bi",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["bod", "tib"],
                names: ["Tibetan"],
                alpha2: "bo",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["bos"],
                names: ["Bosnian"],
                alpha2: "bs",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["bre"],
                names: ["Breton"],
                alpha2: "br",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["bul"],
                names: ["Bulgarian"],
                alpha2: "bg",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["cat"],
                names: ["Catalan", "Valencian"],
                alpha2: "ca",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ces", "cze"],
                names: ["Czech"],
                alpha2: "cs",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["cha"],
                names: ["Chamorro"],
                alpha2: "ch",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["che"],
                names: ["Chechen"],
                alpha2: "ce",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["chu"],
                names: ["Church Slavic", "Old Slavonic", "Church Slavonic", "Old Bulgarian", "Old Church Slavonic"],
                alpha2: "cu",
                scope: "Individual",
                type: "Historical",
        },
        {
                identifiers: ["chv"],
                names: ["Chuvash"],
                alpha2: "cv",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["cor"],
                names: ["Cornish"],
                alpha2: "kw",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["cos"],
                names: ["Corsican"],
                alpha2: "co",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["cre"],
                names: ["Cree"],
                alpha2: "cr",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["cym", "wel"],
                names: ["Welsh"],
                alpha2: "cy",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["dan"],
                names: ["Danish"],
                alpha2: "da",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["deu", "ger"],
                names: ["German"],
                alpha2: "de",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["div"],
                names: ["Divehi", "Dhivehi", "Maldivian"],
                alpha2: "dv",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["dzo"],
                names: ["Dzongkha"],
                alpha2: "dz",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ell", "gre"],
                names: ["Modern Greek", "Modern Greek (1453-)"],
                alpha2: "el",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["eng"],
                names: ["English"],
                alpha2: "en",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["epo"],
                names: ["Esperanto"],
                alpha2: "eo",
                scope: "Individual",
                type: "Constructed",
        },
        {
                identifiers: ["est"],
                names: ["Estonian"],
                alpha2: "et",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["eus", "baq"],
                names: ["Basque"],
                alpha2: "eu",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ewe"],
                names: ["Ewe"],
                alpha2: "ee",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["fao"],
                names: ["Faroese"],
                alpha2: "fo",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["fas", "per"],
                names: ["Persian"],
                alpha2: "fa",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["fij"],
                names: ["Fijian"],
                alpha2: "fj",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["fin"],
                names: ["Finnish"],
                alpha2: "fi",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["fra", "fre"],
                names: ["French"],
                alpha2: "fr",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["fry"],
                names: ["Western Frisian"],
                alpha2: "fy",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ful"],
                names: ["Fulah"],
                alpha2: "ff",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["gla"],
                names: ["Gaelic", "Scottish Gaelic"],
                alpha2: "gd",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["gle"],
                names: ["Irish"],
                alpha2: "ga",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["glg"],
                names: ["Galician"],
                alpha2: "gl",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["glv"],
                names: ["Manx"],
                alpha2: "gv",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["grn"],
                names: ["Guarani"],
                alpha2: "gn",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["guj"],
                names: ["Gujarati"],
                alpha2: "gu",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["hat"],
                names: ["Haitian", "Haitian Creole"],
                alpha2: "ht",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["hau"],
                names: ["Hausa"],
                alpha2: "ha",
                scope: "Macrolanguage",
                type: "Living",
        },
        // Serbo-Croation Code element for 639-1 has been deprecated
        // {
        //         identifiers: ["hbs"],
        //         names: ["Serbo-Croatian"],
        //         alpha2: "sh",
        //         scope: "Macrolanguage",
        //         type: "Living",
        // },
        {
                identifiers: ["heb"],
                names: ["Hebrew"],
                alpha2: "he",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["her"],
                names: ["Herero"],
                alpha2: "hz",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["hin"],
                names: ["Hindi"],
                alpha2: "hi",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["hmo"],
                names: ["Hiri Motu"],
                alpha2: "ho",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["hrv"],
                names: ["Croatian"],
                alpha2: "hr",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["hun"],
                names: ["Hungarian"],
                alpha2: "hu",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["hye", "arm"],
                names: ["Armenian"],
                alpha2: "hy",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ibo"],
                names: ["Igbo"],
                alpha2: "ig",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ido"],
                names: ["Ido"],
                alpha2: "io",
                scope: "Individual",
                type: "Constructed",
        },
        {
                identifiers: ["iii"],
                names: ["Sichuan Yi"],
                alpha2: "ii",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["iku"],
                names: ["Inuktitut"],
                alpha2: "iu",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["ile"],
                names: ["Interlingue"],
                alpha2: "ie",
                scope: "Individual",
                type: "Constructed",
        },
        {
                identifiers: ["ina"],
                names: ["Interlingua", "Interlingua (International Auxiliary Language Association)"],
                alpha2: "ia",
                scope: "Individual",
                type: "Constructed",
        },
        {
                identifiers: ["ind"],
                names: ["Indonesian"],
                alpha2: "id",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ipk"],
                names: ["Inupiaq"],
                alpha2: "ik",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["isl", "ice"],
                names: ["Icelandic"],
                alpha2: "is",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ita"],
                names: ["Italian"],
                alpha2: "it",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["jav"],
                names: ["Javanese"],
                alpha2: "jv",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["jpn"],
                names: ["Japanese"],
                alpha2: "ja",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kal"],
                names: ["Kalaallisut", "Greenlandic"],
                alpha2: "kl",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kan"],
                names: ["Kannada"],
                alpha2: "kn",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kas"],
                names: ["Kashmiri"],
                alpha2: "ks",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kat", "geo"],
                names: ["Georgian"],
                alpha2: "ka",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kau"],
                names: ["Kanuri"],
                alpha2: "kr",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["kaz"],
                names: ["Kazakh"],
                alpha2: "kk",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["khm"],
                names: ["Central Khmer"],
                alpha2: "km",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kik"],
                names: ["Kikuyu", "Gikuyu"],
                alpha2: "ki",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kin"],
                names: ["Kinyarwanda"],
                alpha2: "rw",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kir"],
                names: ["Kirghiz", "Kyrgyz"],
                alpha2: "ky",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kom"],
                names: ["Komi"],
                alpha2: "kv",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["kon"],
                names: ["Kongo"],
                alpha2: "kg",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["kor"],
                names: ["Korean"],
                alpha2: "ko",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kua"],
                names: ["Kuanyama", "Kwanyama"],
                alpha2: "kj",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["kur"],
                names: ["Kurdish"],
                alpha2: "ku",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["lao"],
                names: ["Lao"],
                alpha2: "lo",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["lat"],
                names: ["Latin"],
                alpha2: "la",
                scope: "Individual",
                type: "Historical",
        },
        {
                identifiers: ["lav"],
                names: ["Latvian"],
                alpha2: "lv",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["lim"],
                names: ["Limburgan", "Limburger", "Limburgish"],
                alpha2: "li",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["lin"],
                names: ["Lingala"],
                alpha2: "ln",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["lit"],
                names: ["Lithuanian"],
                alpha2: "lt",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ltz"],
                names: ["Luxembourgish", "Letzeburgesch"],
                alpha2: "lb",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["lub"],
                names: ["Luba-Katanga"],
                alpha2: "lu",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["lug"],
                names: ["Ganda"],
                alpha2: "lg",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["mah"],
                names: ["Marshallese"],
                alpha2: "mh",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["mal"],
                names: ["Malayalam"],
                alpha2: "ml",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["mar"],
                names: ["Marathi"],
                alpha2: "mr",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["mkd", "mac"],
                names: ["Macedonian"],
                alpha2: "mk",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["mlg"],
                names: ["Malagasy"],
                alpha2: "mg",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["mlt"],
                names: ["Maltese"],
                alpha2: "mt",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["mon"],
                names: ["Mongolian"],
                alpha2: "mn",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["mri", "mao"],
                names: ["Maori"],
                alpha2: "mi",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["msa", "may"],
                names: ["Malay"],
                alpha2: "ms",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["mya", "bur"],
                names: ["Burmese"],
                alpha2: "my",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nau"],
                names: ["Nauru"],
                alpha2: "na",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nav"],
                names: ["Navajo", "Navaho"],
                alpha2: "nv",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nbl"],
                names: ["Ndebele, South", "South Ndebele"],
                alpha2: "nr",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nde"],
                names: ["Ndebele, North", "North Ndebele"],
                alpha2: "nd",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ndo"],
                names: ["Ndonga"],
                alpha2: "ng",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nep"],
                names: ["Nepali"],
                alpha2: "ne",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nld", "dut"],
                names: ["Dutch", "Flemish"],
                alpha2: "nl",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nno"],
                names: ["Norwegian Nynorsk", "Nynorsk", "Nynorsk, Norwegian"],
                alpha2: "nn",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nob"],
                names: ["Bokmål, Norwegian", "Norwegian Bokmål"],
                alpha2: "nb",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["nor"],
                names: ["Norwegian"],
                alpha2: "no",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["nya"],
                names: ["Nyanja", "Chichewa", "Chewa" ],
                alpha2: "ny",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["oci"],
                names: ["Occitan (post 1500)"],
                alpha2: "oc",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["oji"],
                names: ["Ojibwa"],
                alpha2: "oj",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["ori"],
                names: ["Oriya"],
                alpha2: "or",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["orm"],
                names: ["Oromo"],
                alpha2: "om",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["oss"],
                names: ["Ossetian", "Ossetic"],
                alpha2: "os",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["pan"],
                names: ["Panjabi", "Punjabi"],
                alpha2: "pa",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["pli"],
                names: ["Pali"],
                alpha2: "pi",
                scope: "Individual",
                type: "Historical",
        },
        {
                identifiers: ["pol"],
                names: ["Polish"],
                alpha2: "pl",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["por"],
                names: ["Portuguese"],
                alpha2: "pt",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["pus"],
                names: ["Pushto"],
                alpha2: "ps",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["que"],
                names: ["Quechua"],
                alpha2: "qu",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["roh"],
                names: ["Romansh"],
                alpha2: "rm",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ron", "rum"],
                names: ["Romanian", "Moldavian", "Moldovan"],
                alpha2: "ro",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["run"],
                names: ["Rundi"],
                alpha2: "rn",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["rus"],
                names: ["Russian"],
                alpha2: "ru",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["sag"],
                names: ["Sango"],
                alpha2: "sg",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["san"],
                names: ["Sanskrit"],
                alpha2: "sa",
                scope: "Macrolanguage",
                type: "Historical",
        },
        {
                identifiers: ["sin"],
                names: ["Sinhala", "Sinhalese"],
                alpha2: "si",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["slk", "slo"],
                names: ["Slovak"],
                alpha2: "sk",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["slv"],
                names: ["Slovenian"],
                alpha2: "sl",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["sme"],
                names: ["Northern Sami"],
                alpha2: "se",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["smo"],
                names: ["Samoan"],
                alpha2: "sm",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["sna"],
                names: ["Shona"],
                alpha2: "sn",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["snd"],
                names: ["Sindhi"],
                alpha2: "sd",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["som"],
                names: ["Somali"],
                alpha2: "so",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["sot"],
                names: ["Southern Sotho"],
                alpha2: "st",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["spa"],
                names: ["Spanish"],
                alpha2: "es",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["sqi", "alb"],
                names: ["Albanian"],
                alpha2: "sq",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["srd"],
                names: ["Sardinian"],
                alpha2: "sc",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["srp"],
                names: ["Serbian"],
                alpha2: "sr",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ssw"],
                names: ["Swati"],
                alpha2: "ss",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["sun"],
                names: ["Sundanese"],
                alpha2: "su",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["swa"],
                names: ["Swahili"],
                alpha2: "sw",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["swe"],
                names: ["Swedish"],
                alpha2: "sv",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tah"],
                names: ["Tahitian"],
                alpha2: "ty",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tam"],
                names: ["Tamil"],
                alpha2: "ta",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tat"],
                names: ["Tatar"],
                alpha2: "tt",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tel"],
                names: ["Telugu"],
                alpha2: "te",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tgk"],
                names: ["Tajik"],
                alpha2: "tg",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tgl"],
                names: ["Tagalog"],
                alpha2: "tl",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tha"],
                names: ["Thai"],
                alpha2: "th",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tir"],
                names: ["Tigrinya"],
                alpha2: "ti",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ton"],
                names: ["Tonga (Tonga Islands)"],
                alpha2: "to",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tsn"],
                names: ["Tswana"],
                alpha2: "tn",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tso"],
                names: ["Tsonga"],
                alpha2: "ts",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tuk"],
                names: ["Turkmen"],
                alpha2: "tk",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["tur"],
                names: ["Turkish"],
                alpha2: "tr",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["twi"],
                names: ["Twi"],
                alpha2: "tw",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["uig"],
                names: ["Uighur", "Uyghur"],
                alpha2: "ug",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["ukr"],
                names: ["Ukrainian"],
                alpha2: "uk",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["urd"],
                names: ["Urdu"],
                alpha2: "ur",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["uzb"],
                names: ["Uzbek"],
                alpha2: "uz",
                scope: "Macrolanguage",
                type: "Living",
        },
        {
                identifiers: ["ven"],
                names: ["Venda"],
                alpha2: "ve",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["vie"],
                names: ["Vietnamese"],
                alpha2: "vi",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["vol"],
                names: ["Volapük"],
                alpha2: "vo",
                scope: "Individual",
                type: "Constructed",
        },
        {
                identifiers: ["wln"],
                names: ["Walloon"],
                alpha2: "wa",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["wol"],
                names: ["Wolof"],
                alpha2: "wo",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["xho"],
                names: ["Xhosa"],
                alpha2: "xh",
                scope: "Individual",
                type: "Living",
        },
        {
                identifiers: ["yid"],
                names: ["Yiddish"],
                alpha2: "yi",
                scope: "Macrolanguage",
                type: "Living"
        },
        {
                identifiers: ["yor"],
                names: ["Yoruba"],
                alpha2: "yo",
                scope: "Individual",
                type: "Living"
        },
        {
                identifiers: ["zha"],
                names: ["Zhuang"],
                alpha2: "za",
                scope: "Macrolanguage",
                type: "Living"
        },
        {
                identifiers: ["zho"],
                names: ["Chinese"],
                alpha2: "zh",
                scope: "Macrolanguage",
                type: "Living"
        },
        {
                identifiers: ["zul"],
                names: ["Zulu"],
                alpha2: "zu",
                scope: "Individual",
                type: "Living"
        }
]
